### ISSUE TITLE
Is this project to be continued?

### ISSUE THREAD

**Issue by OTonGitHub** [free-explorers/veshell#1]

**Comment by PapyElGringo** [comment]
Absolutely ! But the current work are done inside https://github.com/free-explorers/veshell-prototype

**Comment by OTonGitHub** [comment]
Gotchaa, thanks! You guys must have a discussion forum or something right? I felt kinda guilty opening an issue just to ask that hehe.

**Comment by H0R1Z0N** [comment]
They have a discord https://]discord[.gg/rBuHSKaaY7
Remove the backet in the url
