### ISSUE TITLE
[BUG]   build failed WHEN running dart run veshell install -t release      

### ISSUE THREAD

**Issue by mooncoffee1** [free-explorers/veshell#8]
when i try to install using "dart run veshell install -t releas"

I GET THE ERROR

Building package executable... 
Built veshell:veshell.
Checking dependencies...

All dependencies are installed.

Building the rust embedder in release...

cargo build --color always --release

   Compiling veshell v0.1.0 (/home/ananas/Git/veshell/embedder)
   Compiling smithay v0.3.0 (https://github.com/Smithay/smithay?rev=4171247#41712470)

error: failed to run custom build command for `veshell v0.1.0 (/home/ananas/Git/veshell/embedder)`

Caused by:
  process didn't exit successfully: `/home/ananas/Git/veshell/embedder/target/release/build/veshell-5c63a28aec5a9a12/build-script-build` (exit status: 101)
  --- stdout
  FLUTTER_ENGINE_BUILD: release

  --- stderr
  thread 'main' panicked at build.rs:43:66:
  called `Option::unwrap()` on a `None` value
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

╭─ananas@archlinux ~/Git/veshell ‹main› 
╰─$ RUST_BACKTRACE=1 cargo build --release                                                     101 ↵

error: could not find `Cargo.toml` in `/home/ananas/Git/veshell` or any parent directory

**Comment by PapyElGringo** [comment]
Do you run the command from the veshell folder?

**Comment by PapyElGringo** [comment]
Do you have Flutter installed on your system and in path?

**Comment by mooncoffee1** [comment]
alr, it got installed, looks good soo far, but no settings, no volume and brighness OSD, still nothing :(, looks good soo continue working on it ;)

**Comment by PapyElGringo** [comment]
> alr, it got installed, looks good soo far, but no settings, no volume and brighness OSD, still nothing :(, looks good soo continue working on it ;)

Yeah it still misses a lot of features but I want to invite more people to contribute to split the work effort!

Thanks for trying ! I'm glad you liked it so far!

**Comment by mooncoffee1** [comment]
saddly cant program, ik some linux stuff but idk Flutter ;(

**Comment by PapyElGringo** [comment]
Well time to learn :D
